### PR TITLE
Skip regions without available data in `getSortedDataObjects`

### PR DESCRIPTION
**Pull request by MaPePeR**
This seems to fix the filters being unavailable when not all region data is available.

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]
LGTM, thanks!
I'm merging, then we can check https://rtlive.de/preview/global.html to see if there are any problems.

**Comment by MaPePeR** [comment]
It fixes the bug, that the country selector now works again, but if you select a country before selecting a scope the region comparison plot at the top is shown in a weird way, because the scope is unset. Fixes itself when you clicks one of the buttons.

Not really sure how to fix this. Maybe set a default scope value in `setFilter`?

**Comment by michaelosthege** [comment]
I can't reproduce what you're describing. Can you post a screenshot? Which browser?

For me the scope buttons are initialized and shown at default values (Firefox, Edge).

**Comment by MaPePeR** [comment]
Using the preview in Chrome:
rtlive de_preview_global html (1)

`CURRENT_SCOPE` is still `null`. Only occurs, when there is data still being processed, I think.

**Comment by michaelosthege** [comment]
With Chrome 90.0.4430.85 I don't see this at all. All the processing happens so fast..

What did happen to me is that the graph for 7-day infection rate was broken until the JSONs were all updated. They are cached at the Amazon CloudFront level and also in the browser. With a private session the cache was no longer a problem.

**Pull request merged**
